"""
Django settings for homework1 project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Firebase 設定
try:
    import firebase_admin
    from firebase_admin import credentials, firestore
    
    # Firebase 初始化（需要服務帳號金鑰檔案）
    FIREBASE_CREDENTIALS_PATH = BASE_DIR / 'firebase-credentials.json'
    
    if not firebase_admin._apps:
        if FIREBASE_CREDENTIALS_PATH.exists():
            cred = credentials.Certificate(str(FIREBASE_CREDENTIALS_PATH))
            firebase_admin.initialize_app(cred)
        else:
            # 如果沒有金鑰檔案，嘗試使用環境變數
            # 生產環境建議使用環境變數 GOOGLE_APPLICATION_CREDENTIALS
            if os.getenv('GOOGLE_APPLICATION_CREDENTIALS'):
                firebase_admin.initialize_app()
            else:
                print("⚠️  警告：未找到 Firebase 憑證檔案，Firebase 功能可能無法使用")
                print(f"   請將 firebase-credentials.json 放在：{FIREBASE_CREDENTIALS_PATH}")
    
    # 取得 Firestore 資料庫實例（可在其他模組中導入）
    db = firestore.client()
except ImportError:
    print("⚠️  警告：firebase-admin 未安裝，請執行：pip install firebase-admin")
    db = None
except Exception as e:
    print(f"⚠️  警告：Firebase 初始化失敗：{e}")
    db = None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!+&$l&yrg)aeki!5k!yms9zbvd!7$6&o!st-fzonl7!z2u*l^%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
]


LOGIN_REDIRECT_URL = '/user/'       # 使用者登入成功後導向會員中心
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/userlogin/'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'CampingData.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CampingData.wsgi.application'

#發送email的設定
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # 或 465 (如果使用 SSL)
EMAIL_USE_TLS = True # 或 EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'campingdata.2025@gmail.com'
EMAIL_HOST_PASSWORD = 'dutp sswe kyhm ucoe'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
AUTH_USER_MODEL = 'myapp.User'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# 此專案完全使用 Firebase Firestore 作為資料庫
# 不使用 MySQL 或其他傳統資料庫
# 所有資料操作都通過 myapp/firebase_service.py 中的 Firebase 服務層進行
#
# Django 的 DATABASES 設定僅作為佔位用，避免 Django 框架錯誤
# 實際上所有資料都儲存在 Firebase Firestore 中
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_firebase_placeholder.sqlite3',  # 佔位用，不會實際使用
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
